services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: appdb
    volumes:
      - db-storage:/var/lib/postgresql
      - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  db-storage:
